#define FPS 60

#define WINDOW_WIDTH 1600
#define WINDOW_HEIGTH 900
#define WINDOW_TITLE "bunker"

#define GAME_FRAME_SCALE 0.025
#define GAME_FRAME_OFFSET_X 0*-WINDOW_WIDTH/8
#define GAME_FRAME_OFFSET_Y 0*WINDOW_HEIGTH/2
